/*
 * File:           TracksHandler.java
 * Date:           24 February 2010  15:44
 *
 * @author  hellhand
 * @version generated by NetBeans XML module
 */
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package org.mimp.parser;

import org.xml.sax.AttributeList;
import org.xml.sax.SAXException;

/**
 * 
 * @author hellhand
 */
public interface TracksHandler {

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_difficulty(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_downHill(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_uphill(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_distance(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_title(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_created(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * An empty element event handling method.
     * 
     * @param data
     *            value or null
     */
    public void handle_start(final AttributeList meta) throws SAXException;

    /**
     * 
     * A container element start event handling method.
     * 
     * @param meta
     *            attributes
     */
    public void start_trail(final AttributeList meta) throws SAXException;

    /**
     * 
     * A container element end event handling method.
     */
    public void end_trail() throws SAXException;

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_name(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_owner(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_rating(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * A container element start event handling method.
     * 
     * @param meta
     *            attributes
     */
    public void start_trails(final AttributeList meta) throws SAXException;

    /**
     * 
     * A container element end event handling method.
     */
    public void end_trails() throws SAXException;

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_activity(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_tps(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * An object containing the track return method
     * 
     * @return track list
     */
    public Tracks getTracks();
}
