/*
 * File:           GPXHandler.java
 * Date:           18 February 2010  10:03
 *
 * @author  hellhand
 * @version generated by NetBeans XML module
 */
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package org.mimp.sax.gpx;

import org.xml.sax.AttributeList;
import org.xml.sax.SAXException;

/**
 * 
 * @author hellhand
 */
public interface GPXHandler {

    /**
     * 
     * A container element start event handling method.
     * 
     * @param meta
     *            attributes
     */
    public void start_wptinfos(final AttributeList meta) throws SAXException;

    /**
     * 
     * A container element end event handling method.
     */
    public void end_wptinfos() throws SAXException;

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_elemin(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_desc(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * A container element start event handling method.
     * 
     * @param meta
     *            attributes
     */
    public void start_gpxmedia(final AttributeList meta) throws SAXException;

    /**
     * 
     * A container element end event handling method.
     */
    public void end_gpxmedia() throws SAXException;

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_sym(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_type(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * A container element start event handling method.
     * 
     * @param meta
     *            attributes
     */
    public void start_extensions(final AttributeList meta) throws SAXException;

    /**
     * 
     * A container element end event handling method.
     */
    public void end_extensions() throws SAXException;

    /**
     * 
     * A container element start event handling method.
     * 
     * @param meta
     *            attributes
     */
    public void start_publisher(final AttributeList meta) throws SAXException;

    /**
     * 
     * A container element end event handling method.
     */
    public void end_publisher() throws SAXException;

    /**
     * 
     * A container element start event handling method.
     * 
     * @param meta
     *            attributes
     */
    public void start_author(final AttributeList meta) throws SAXException;

    /**
     * 
     * A container element end event handling method.
     */
    public void end_author() throws SAXException;

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_distance(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_time(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_title(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * A container element start event handling method.
     * 
     * @param meta
     *            attributes
     */
    public void start_trkseg(final AttributeList meta) throws SAXException;

    /**
     * 
     * A container element end event handling method.
     */
    public void end_trkseg() throws SAXException;

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_name(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_activitytype(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * A container element start event handling method.
     * 
     * @param meta
     *            attributes
     */
    public void start_gpxinfos(final AttributeList meta) throws SAXException;

    /**
     * 
     * A container element end event handling method.
     */
    public void end_gpxinfos() throws SAXException;

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_year(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * A container element start event handling method.
     * 
     * @param meta
     *            attributes
     */
    public void start_gpx(final AttributeList meta) throws SAXException;

    /**
     * 
     * A container element end event handling method.
     */
    public void end_gpx() throws SAXException;

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_realdistance(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_ele(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * A container element start event handling method.
     * 
     * @param meta
     *            attributes
     */
    public void start_metadata(final AttributeList meta) throws SAXException;

    /**
     * 
     * A container element end event handling method.
     */
    public void end_metadata() throws SAXException;

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_thl(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * A container element start event handling method.
     * 
     * @param meta
     *            attributes
     */
    public void start_trkpt(final AttributeList meta) throws SAXException;

    /**
     * 
     * A container element end event handling method.
     */
    public void end_trkpt() throws SAXException;

    /**
     * 
     * A container element start event handling method.
     * 
     * @param meta
     *            attributes
     */
    public void start_trkinfos(final AttributeList meta) throws SAXException;

    /**
     * 
     * A container element end event handling method.
     */
    public void end_trkinfos() throws SAXException;

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_thg(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * A container element start event handling method.
     * 
     * @param meta
     *            attributes
     */
    public void start_trk(final AttributeList meta) throws SAXException;

    /**
     * 
     * A container element end event handling method.
     */
    public void end_trk() throws SAXException;

    /**
     * 
     * A container element start event handling method.
     * 
     * @param meta
     *            attributes
     */
    public void start_rte(final AttributeList meta) throws SAXException;

    /**
     * 
     * A container element end event handling method.
     */
    public void end_rte() throws SAXException;

    /**
     * 
     * A container element start event handling method.
     * 
     * @param meta
     *            attributes
     */
    public void start_copyright(final AttributeList meta) throws SAXException;

    /**
     * 
     * A container element end event handling method.
     */
    public void end_copyright() throws SAXException;

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_url(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * A container element start event handling method.
     * 
     * @param meta
     *            attributes
     */
    public void start_rteinfos(final AttributeList meta) throws SAXException;

    /**
     * 
     * A container element end event handling method.
     */
    public void end_rteinfos() throws SAXException;

    /**
     * 
     * An empty element event handling method.
     * 
     * @param data
     *            value or null
     */
    public void handle_bounds(final AttributeList meta) throws SAXException;

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_duration(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * A container element start event handling method.
     * 
     * @param meta
     *            attributes
     */
    public void start_rtept(final AttributeList meta) throws SAXException;

    /**
     * 
     * A container element end event handling method.
     */
    public void end_rtept() throws SAXException;

    /**
     * 
     * A container element start event handling method.
     * 
     * @param meta
     *            attributes
     */
    public void start_wpt(final AttributeList meta) throws SAXException;

    /**
     * 
     * A container element end event handling method.
     */
    public void end_wpt() throws SAXException;

    /**
     * 
     * A container element start event handling method.
     * 
     * @param meta
     *            attributes
     */
    public void start_source(final AttributeList meta) throws SAXException;

    /**
     * 
     * A container element end event handling method.
     */
    public void end_source() throws SAXException;

    /**
     * 
     * An empty element event handling method.
     * 
     * @param data
     *            value or null
     */
    public void handle_email(final AttributeList meta) throws SAXException;

    /**
     * 
     * A container element start event handling method.
     * 
     * @param meta
     *            attributes
     */
    public void start_medias(final AttributeList meta) throws SAXException;

    /**
     * 
     * A container element end event handling method.
     */
    public void end_medias() throws SAXException;

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_bearing(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_radius(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_characteristic(final String data,
            final AttributeList meta) throws SAXException;

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_maxspeed(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * A container element start event handling method.
     * 
     * @param meta
     *            attributes
     */
    public void start_media(final AttributeList meta) throws SAXException;

    /**
     * 
     * A container element end event handling method.
     */
    public void end_media() throws SAXException;

    /**
     * 
     * A data element event handling method.
     * 
     * @param data
     *            value or null
     * @param meta
     *            attributes
     */
    public void handle_elemax(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * @throws SAXException
     */
    public void start_content(final AttributeList meta) throws SAXException;

    /**
     * 
     * @param data
     * @param meta
     * @throws SAXException
     */
    public void handle_content(final String data, final AttributeList meta)
            throws SAXException;

    /**
     * 
     * @throws SAXException
     */
    public void end_content() throws SAXException;

    /**
     * 
     * @return object created by the handler
     */
    public GPXObject getGPXObject();
}
